name: lucky_games
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  build_runner: ^2.4.8
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.7.2+3
  flutter_custom_dialog: ^1.3.0
  in_app_review: ^2.0.8
  flutter_screenutil: ^5.9.0
  flutter_shake_animated: ^0.0.5
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  yoda: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/onboarding/
    - assets/landing/
    - assets/bg/
    - assets/difficulty/
    - assets/match_pairs/
    - assets/minesweeper/
    - assets/shared/
    - assets/settings/
  fonts:
    - family: Genos
      fonts:
        - asset: assets/fonts/Genos/static/Genos-Regular.ttf
        - asset: assets/fonts/Genos/static/Genos-Medium.ttf
        - asset: assets/fonts/Genos/static/Genos-SemiBold.ttf
        - asset: assets/fonts/Genos/static/Genos-Bold.ttf
        - asset: assets/fonts/Genos/static/Genos-ExtraBold.ttf
